export const enum IMPORT {
  MEMBER_BASIC = 1,
  MEMBER_RECORD = 2,
  STAFF = 3,
  MEMBER_CARD_BASIC = 4,
  MEMBER_CARD_PRICE = 5,
  DEPOSIT = 16,
  TEAM_COURSE = 15,
  PERSONAL_BASIC = 6,
  PERSONAL_PRICE = 7,
  SUPPORT_SOLD_SHOP = 8,
  SUPPORT_CONSUME_SHOP = 9,
  SOLD_MEMBER_CARD = 10,
  SOLD_MEMBER_CARD_ENTER_TIME = 11,
  SOLD_PERSONAL_COURSE = 12,
  SOLD_LEASE = 13,
  SOLD_DEPOSIT = 14,
  FILE_SAVE_TYPE = 1
}
export const enum IMPORT_STATUS {
  SUCCESS = 1,
  IMPORTING = 2,
  ERROR = 3
}
