export const enum CABINET {
  USE_STATUS_AVAILABLE = 1, // 可用状态
  USE_STATUS_USING = 1, // 使用中
  USE_STATUS_BROKEN = 1, // 版本1
  VERSION_2 = 2, // 版本2
  CABINET_BUSINESS_TYPE_AVAILABLE = 1,
  CABINET_BUSINESS_TYPE_USING = 2,
  CABINET_BUSINESS_TYPE_BROKEN = 3,
  CABINET_BUSINESS_TYPE_REPAIR = 4
}

export const enum CABINET_REASONS {
  OTHERS = 3
}
