export const enum SHOP_MEMBER {
  PUBLISH_CHANNEL_1 = 1,
  PUBLISH_CHANNEL_2 = 2,
  CARD_TYPE_1 = 1,
  CARD_TYPE_2 = 2,
  PRICE_SETTING_1 = 1,
  PRICE_SETTING_2 = 2,
  ADMISSION_TIME_1 = 1,
  ADMISSION_TIME_2 = 2
}
