/**
 * 品牌储值卡搜索事件
 */
export const BRAND_PRODUCT_CARD_DEPOSIT_KEYWORDS_SEARCH =
  'BRAND_PRODUCT_CARD_DEPOSIT_KEYWORDS_SEARCH'
/**
 * 门店储值卡搜索事件
 */
export const BRAND_PRODUCT_CARD_MEMBER_KEYWORDS_SEARCH =
  'BRAND_PRODUCT_CARD_MEMBER_KEYWORDS_SEARCH'
/**
 * 门店储值卡搜索事件
 */
export const SHOP_PRODUCT_CARD_DEPOSIT_KEYWORDS_SEARCH =
  'SHOP_PRODUCT_CARD_DEPOSIT_KEYWORDS_SEARCH'
/**
 * 门店会员卡搜索事件
 */
export const SHOP_PRODUCT_CARD_MEMBER_KEYWORDS_SEARCH =
  'SHOP_PRODUCT_CARD_DEPOSIT_KEYWORDS_SEARCH'
