/**
 * 品牌储值卡搜索事件
 */
export const BRAND_PRODUCT_CARD_DEPOSIT_KEYWORDS_SEARCH =
  'BRAND_PRODUCT_CARD_DEPOSIT_KEYWORDS_SEARCH'
/**
 * 门店储值卡搜索事件
 */
export const BRAND_PRODUCT_CARD_MEMBER_KEYWORDS_SEARCH =
  'BRAND_PRODUCT_CARD_MEMBER_KEYWORDS_SEARCH'
/**
 * 门店储值卡搜索事件
 */
export const SHOP_PRODUCT_CARD_DEPOSIT_KEYWORDS_SEARCH =
  'SHOP_PRODUCT_CARD_DEPOSIT_KEYWORDS_SEARCH'
/**
 * 门店会员卡搜索事件
 */
export const SHOP_PRODUCT_CARD_MEMBER_KEYWORDS_SEARCH =
  'SHOP_PRODUCT_CARD_DEPOSIT_KEYWORDS_SEARCH'
/**
 * 门店库存搜索事件
 */
export const SHOP_STORE_STOCK_KEYWORDS_SEARCH =
  'SHOP_STORE_STOCK_KEYWORDS_SEARCH'
/**
 * 云小店发货订单搜索事件
 */
export const SHOP_STORE_ORDER_KEYWORDS_SEARCH =
  'SHOP_STORE_ORDER_KEYWORDS_SEARCH'
