<template>
  <section class="container-basis">
    <st-avatar-upload></st-avatar-upload>
    <st-picture-upload></st-picture-upload>
    <st-avatar-upload></st-avatar-upload>
    <st-picture-upload></st-picture-upload>
    <st-avatar-upload></st-avatar-upload>
    <st-picture-upload></st-picture-upload>
    <st-avatar-upload></st-avatar-upload>
    <st-picture-upload></st-picture-upload>
    <st-avatar-upload></st-avatar-upload>
    <st-picture-upload></st-picture-upload>
    <st-avatar-upload></st-avatar-upload>
    <st-picture-upload></st-picture-upload>
    <st-avatar-upload></st-avatar-upload>
    <st-picture-upload></st-picture-upload>
    <st-avatar-upload></st-avatar-upload>
    <st-picture-upload></st-picture-upload>
  </section>
</template>
