export enum CLASS_STATUS {
  UNPUBLISH = 1,
  PUBLISH_UNSTARTED = 2,
  SIGNING_UNCLASSED = 3,
  SIGNING_CLASSED = 4,
  CLASS_FAILED = 5,
  CLASSED = 6,
  CLASS_END = 7
}
export enum COURSE_TYPE {
  FIXED_COURSE = 1, //  固定排课
  AUTO_COURSE = 2
}
