// 品牌下财务资金薪资模板枚举
export const enum SALAY_TEMPLATE {
  PERFORMANCE_TYPE_1 = 1,
  PERFORMANCE_TYPE_2 = 2,
  PERFORMANCE_TYPE_3 = 3,
  PERFORMANCE_MODE_1 = 1,
  PERFORMANCE_MODE_2 = 2,
  PERFORMANCE_MODE_3 = 3
}
